services:
  app:
    image: nextjs-boilerplate/app
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nextjs-boilerplate-app
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ..:/app
    environment:
      - NODE_ENV=development
      - TZ=Asia/Tokyo
    restart: unless-stopped
    
